[project]
name = "ssm2mqtt"
version = "0.2.2"
description = ""
authors = [
    {name = "meronepy",email = "203420124+meronepy@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "gomalock @ git+https://github.com/meronepy/gomalock.git@v0.3.0",
    "aiomqtt (>=2.4.0,<3.0.0)"
]

[tool.poetry]
packages = [{include = "ssm2mqtt", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
